DROP DATABASE IF EXISTS fg;
CREATE DATABASE fg;
USE fg;

CREATE TABLE Congresos(
IDCongreso INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
Tematica VARCHAR(50) NOT NULL,
FechaInicio DATE NOT NULL,
PrecioInscripcion INT(10) NOT NULL
);

CREATE TABLE Expositores(
IDExpositor INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
Nombre VARCHAR(80) NOT NULL,
Pais VARCHAR(50) NOT NULL,
Especialidad VARCHAR(50) NOT NULL
);

CREATE TABLE Charlas(
IDCharla INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
IDCongreso INT NOT NULL,
IDExpositor INT NOT NULL,
TituloCharla VARCHAR(100) NOT NULL,
AsistentesEstimados INT(10) NOT NULL,
DuracionMinutos INT(10) NOT NULL,
FOREIGN KEY (IDCongreso) REFERENCES Congresos(IDCongreso),
FOREIGN KEY (IDExpositor) REFERENCES Expositores(IDExpositor)
);